### ISSUE TITLE
Your code is great!

### ISSUE THREAD

**Issue by GavinRay97** [ilikdoge/xe#1]
Just wanted to say thanks for open-sourcing this, I've used your repo to learn more about `io_uring`'s API and performant I/O. And I really enjoy your style of C++ programming (C with a dash of C++, much more readable than most C++ code).

**Comment by davidzeng0** [comment]
Thanks :)

**Comment by davidzeng0** [comment]
That reminded me to add a few more comments explaining some logic. Here is that commit:

https://github.com/davidzeng0/xe/commit/6e2147f55862a8205fade22edb0efc8a038a543b

**Comment by GavinRay97** [comment]
Do you have an email/discord by chance?

(If you're interested in chatting more about low-level perf and I/O stuff. I'm interested in it from a database perspective, so mix of disk I/O and network I/O)

Mine is:
![image](https://user-images.githubusercontent.com/26604994/206539756-646b1bd8-633d-447b-88ae-33c18e0dd828.png)

**Comment by davidzeng0** [comment]
I've added you on discord
